In [1]:
import torch

x = torch.randn([3, 4, 5])
print(x.shape)


torch.Size([3, 4, 5])


In [2]:
x

tensor([[[ 0.7658,  0.6226,  0.6717,  0.0662, -1.0256],
         [-2.8379, -1.2581,  0.9488, -0.7173,  0.9952],
         [-1.5395,  0.3030,  2.0150,  1.3423,  0.0315],
         [ 1.1969, -0.2895, -0.3462, -1.5628,  0.1420]],

        [[ 1.2434,  1.3299,  1.6568,  1.3563, -1.0754],
         [ 1.5177,  0.8218,  0.3257, -2.5025, -0.1324],
         [ 0.2868, -1.0215,  0.8582, -1.6023,  0.0504],
         [ 0.9003, -1.3893,  0.2230,  0.7178,  1.3689]],

        [[ 1.4601,  1.0456, -1.3448, -0.0512, -0.3065],
         [-1.0301, -0.6792,  0.2995,  0.1646, -0.7947],
         [ 0.4027,  1.0534, -0.4602,  0.6796,  0.3022],
         [ 1.0796, -0.2235, -0.3241, -0.2496,  2.3131]]])

In [5]:
torch.pow(x, 2).shape


torch.Size([3, 4, 5])

In [7]:
torch.sqrt(torch.pow(x, 2).mean(dim=-1, keepdim=True)).shape

torch.Size([3, 4, 1])

In [5]:
import torch
x = torch.randn([3, 4, 5])
max_val = torch.max(x, dim=-1, keepdim=True)[0]
max_val



tensor([[[0.4803],
         [1.7673],
         [0.9850],
         [0.7846]],

        [[1.3694],
         [0.5279],
         [0.7645],
         [3.8881]],

        [[1.0962],
         [1.9859],
         [0.2020],
         [0.6675]]])

In [17]:
x = torch.randn([3, 4, 5])

In [16]:
torch.arange(10, dtype=torch.long).shape


torch.Size([10])

In [18]:
x

tensor([[[ 0.4261,  0.2965, -0.6432, -0.4145,  0.9939],
         [-0.1266,  1.7398, -1.9448,  0.4058, -0.3162],
         [-0.6754,  0.5382,  0.5755, -0.0928,  2.0360],
         [-0.8421, -1.2217,  2.1076,  0.2309, -0.2821]],

        [[ 0.4014,  0.1394,  2.0088,  1.3208, -0.9650],
         [ 0.0048,  1.9687,  0.5081, -0.1780,  0.3074],
         [ 0.5716,  0.1326, -0.4747,  0.0950,  0.3835],
         [-0.5189,  0.0647, -1.1119,  0.7874, -1.3882]],

        [[-0.6415,  0.8218, -0.9574,  0.9448,  0.7023],
         [ 0.2367, -1.2225,  0.6069, -0.0325,  0.7544],
         [-0.4208,  1.4377,  0.4920,  0.5257, -0.3870],
         [ 1.3711,  0.4020,  0.2347,  0.2145, -0.3299]]])

In [19]:
x + torch.arange(10, dtype=torch.long)

RuntimeError: The size of tensor a (5) must match the size of tensor b (10) at non-singleton dimension 2